[package]
name = "random-access-memory"
version = "0.0.1"
license = "Apache-2.0"
repository = "https://github.com/datrs/random-access-memory"
documentation = "https://docs.rs/random-access-memory"
description = "Continuously read,write to memory using random offsets and lengths"
authors = ["datrs <yoshuawuyts@gmail.com>"]

[dependencies]
random-access-storage = { path = '../random-access-storage' }
# random-access-storage = "0.2.0"
failure = "0.1.1"
failure_derive = "0.1.1"
